// Auto-generated file - do not edit manually
// Generated by generate-svg-imports.js

import adSvg from '../assets/flags/ad.svg';
import aeSvg from '../assets/flags/ae.svg';
import afSvg from '../assets/flags/af.svg';
import agSvg from '../assets/flags/ag.svg';
import aiSvg from '../assets/flags/ai.svg';
import alSvg from '../assets/flags/al.svg';
import amSvg from '../assets/flags/am.svg';
import aoSvg from '../assets/flags/ao.svg';
import aqSvg from '../assets/flags/aq.svg';
import arSvg from '../assets/flags/ar.svg';
import arabSvg from '../assets/flags/arab.svg';
import asSvg from '../assets/flags/as.svg';
import aseanSvg from '../assets/flags/asean.svg';
import atSvg from '../assets/flags/at.svg';
import auSvg from '../assets/flags/au.svg';
import awSvg from '../assets/flags/aw.svg';
import axSvg from '../assets/flags/ax.svg';
import azSvg from '../assets/flags/az.svg';
import baSvg from '../assets/flags/ba.svg';
import bbSvg from '../assets/flags/bb.svg';
import bdSvg from '../assets/flags/bd.svg';
import beSvg from '../assets/flags/be.svg';
import bfSvg from '../assets/flags/bf.svg';
import bgSvg from '../assets/flags/bg.svg';
import bhSvg from '../assets/flags/bh.svg';
import biSvg from '../assets/flags/bi.svg';
import bjSvg from '../assets/flags/bj.svg';
import blSvg from '../assets/flags/bl.svg';
import bmSvg from '../assets/flags/bm.svg';
import bnSvg from '../assets/flags/bn.svg';
import boSvg from '../assets/flags/bo.svg';
import bqSvg from '../assets/flags/bq.svg';
import brSvg from '../assets/flags/br.svg';
import bsSvg from '../assets/flags/bs.svg';
import btSvg from '../assets/flags/bt.svg';
import bvSvg from '../assets/flags/bv.svg';
import bwSvg from '../assets/flags/bw.svg';
import bySvg from '../assets/flags/by.svg';
import bzSvg from '../assets/flags/bz.svg';
import caSvg from '../assets/flags/ca.svg';
import ccSvg from '../assets/flags/cc.svg';
import cdSvg from '../assets/flags/cd.svg';
import ceftaSvg from '../assets/flags/cefta.svg';
import cfSvg from '../assets/flags/cf.svg';
import cgSvg from '../assets/flags/cg.svg';
import chSvg from '../assets/flags/ch.svg';
import ciSvg from '../assets/flags/ci.svg';
import ckSvg from '../assets/flags/ck.svg';
import clSvg from '../assets/flags/cl.svg';
import cmSvg from '../assets/flags/cm.svg';
import cnSvg from '../assets/flags/cn.svg';
import coSvg from '../assets/flags/co.svg';
import cpSvg from '../assets/flags/cp.svg';
import crSvg from '../assets/flags/cr.svg';
import cuSvg from '../assets/flags/cu.svg';
import cvSvg from '../assets/flags/cv.svg';
import cwSvg from '../assets/flags/cw.svg';
import cxSvg from '../assets/flags/cx.svg';
import cySvg from '../assets/flags/cy.svg';
import czSvg from '../assets/flags/cz.svg';
import deSvg from '../assets/flags/de.svg';
import dgSvg from '../assets/flags/dg.svg';
import djSvg from '../assets/flags/dj.svg';
import dkSvg from '../assets/flags/dk.svg';
import dmSvg from '../assets/flags/dm.svg';
import doSvg from '../assets/flags/do.svg';
import dzSvg from '../assets/flags/dz.svg';
import eacSvg from '../assets/flags/eac.svg';
import ecSvg from '../assets/flags/ec.svg';
import eeSvg from '../assets/flags/ee.svg';
import egSvg from '../assets/flags/eg.svg';
import ehSvg from '../assets/flags/eh.svg';
import erSvg from '../assets/flags/er.svg';
import es_ctSvg from '../assets/flags/es-ct.svg';
import es_gaSvg from '../assets/flags/es-ga.svg';
import es_pvSvg from '../assets/flags/es-pv.svg';
import esSvg from '../assets/flags/es.svg';
import etSvg from '../assets/flags/et.svg';
import euSvg from '../assets/flags/eu.svg';
import example_usSvg from '../assets/flags/example-us.svg';
import fiSvg from '../assets/flags/fi.svg';
import fjSvg from '../assets/flags/fj.svg';
import fkSvg from '../assets/flags/fk.svg';
import fmSvg from '../assets/flags/fm.svg';
import foSvg from '../assets/flags/fo.svg';
import frSvg from '../assets/flags/fr.svg';
import gaSvg from '../assets/flags/ga.svg';
import gb_engSvg from '../assets/flags/gb-eng.svg';
import gb_nirSvg from '../assets/flags/gb-nir.svg';
import gb_sctSvg from '../assets/flags/gb-sct.svg';
import gb_wlsSvg from '../assets/flags/gb-wls.svg';
import gbSvg from '../assets/flags/gb.svg';
import gdSvg from '../assets/flags/gd.svg';
import geSvg from '../assets/flags/ge.svg';
import gfSvg from '../assets/flags/gf.svg';
import ggSvg from '../assets/flags/gg.svg';
import ghSvg from '../assets/flags/gh.svg';
import giSvg from '../assets/flags/gi.svg';
import glSvg from '../assets/flags/gl.svg';
import gmSvg from '../assets/flags/gm.svg';
import gnSvg from '../assets/flags/gn.svg';
import gpSvg from '../assets/flags/gp.svg';
import gqSvg from '../assets/flags/gq.svg';
import grSvg from '../assets/flags/gr.svg';
import gsSvg from '../assets/flags/gs.svg';
import gtSvg from '../assets/flags/gt.svg';
import guSvg from '../assets/flags/gu.svg';
import gwSvg from '../assets/flags/gw.svg';
import gySvg from '../assets/flags/gy.svg';
import hkSvg from '../assets/flags/hk.svg';
import hmSvg from '../assets/flags/hm.svg';
import hnSvg from '../assets/flags/hn.svg';
import hrSvg from '../assets/flags/hr.svg';
import htSvg from '../assets/flags/ht.svg';
import huSvg from '../assets/flags/hu.svg';
import icSvg from '../assets/flags/ic.svg';
import idSvg from '../assets/flags/id.svg';
import ieSvg from '../assets/flags/ie.svg';
import ilSvg from '../assets/flags/il.svg';
import imSvg from '../assets/flags/im.svg';
import inSvg from '../assets/flags/in.svg';
import ioSvg from '../assets/flags/io.svg';
import iqSvg from '../assets/flags/iq.svg';
import irSvg from '../assets/flags/ir.svg';
import isSvg from '../assets/flags/is.svg';
import itSvg from '../assets/flags/it.svg';
import jeSvg from '../assets/flags/je.svg';
import jmSvg from '../assets/flags/jm.svg';
import joSvg from '../assets/flags/jo.svg';
import jpSvg from '../assets/flags/jp.svg';
import keSvg from '../assets/flags/ke.svg';
import kgSvg from '../assets/flags/kg.svg';
import khSvg from '../assets/flags/kh.svg';
import kiSvg from '../assets/flags/ki.svg';
import kmSvg from '../assets/flags/km.svg';
import knSvg from '../assets/flags/kn.svg';
import kpSvg from '../assets/flags/kp.svg';
import krSvg from '../assets/flags/kr.svg';
import kwSvg from '../assets/flags/kw.svg';
import kySvg from '../assets/flags/ky.svg';
import kzSvg from '../assets/flags/kz.svg';
import laSvg from '../assets/flags/la.svg';
import lbSvg from '../assets/flags/lb.svg';
import lcSvg from '../assets/flags/lc.svg';
import liSvg from '../assets/flags/li.svg';
import lkSvg from '../assets/flags/lk.svg';
import lrSvg from '../assets/flags/lr.svg';
import lsSvg from '../assets/flags/ls.svg';
import ltSvg from '../assets/flags/lt.svg';
import luSvg from '../assets/flags/lu.svg';
import lvSvg from '../assets/flags/lv.svg';
import lySvg from '../assets/flags/ly.svg';
import maSvg from '../assets/flags/ma.svg';
import mcSvg from '../assets/flags/mc.svg';
import mdSvg from '../assets/flags/md.svg';
import meSvg from '../assets/flags/me.svg';
import mfSvg from '../assets/flags/mf.svg';
import mgSvg from '../assets/flags/mg.svg';
import mhSvg from '../assets/flags/mh.svg';
import mkSvg from '../assets/flags/mk.svg';
import mlSvg from '../assets/flags/ml.svg';
import mmSvg from '../assets/flags/mm.svg';
import mnSvg from '../assets/flags/mn.svg';
import moSvg from '../assets/flags/mo.svg';
import mpSvg from '../assets/flags/mp.svg';
import mqSvg from '../assets/flags/mq.svg';
import mrSvg from '../assets/flags/mr.svg';
import msSvg from '../assets/flags/ms.svg';
import mtSvg from '../assets/flags/mt.svg';
import muSvg from '../assets/flags/mu.svg';
import mvSvg from '../assets/flags/mv.svg';
import mwSvg from '../assets/flags/mw.svg';
import mxSvg from '../assets/flags/mx.svg';
import mySvg from '../assets/flags/my.svg';
import mzSvg from '../assets/flags/mz.svg';
import naSvg from '../assets/flags/na.svg';
import ncSvg from '../assets/flags/nc.svg';
import neSvg from '../assets/flags/ne.svg';
import nfSvg from '../assets/flags/nf.svg';
import ngSvg from '../assets/flags/ng.svg';
import niSvg from '../assets/flags/ni.svg';
import nlSvg from '../assets/flags/nl.svg';
import noSvg from '../assets/flags/no.svg';
import npSvg from '../assets/flags/np.svg';
import nrSvg from '../assets/flags/nr.svg';
import nuSvg from '../assets/flags/nu.svg';
import nzSvg from '../assets/flags/nz.svg';
import omSvg from '../assets/flags/om.svg';
import paSvg from '../assets/flags/pa.svg';
import pcSvg from '../assets/flags/pc.svg';
import peSvg from '../assets/flags/pe.svg';
import pfSvg from '../assets/flags/pf.svg';
import pgSvg from '../assets/flags/pg.svg';
import phSvg from '../assets/flags/ph.svg';
import pkSvg from '../assets/flags/pk.svg';
import plSvg from '../assets/flags/pl.svg';
import pmSvg from '../assets/flags/pm.svg';
import pnSvg from '../assets/flags/pn.svg';
import prSvg from '../assets/flags/pr.svg';
import psSvg from '../assets/flags/ps.svg';
import ptSvg from '../assets/flags/pt.svg';
import pwSvg from '../assets/flags/pw.svg';
import pySvg from '../assets/flags/py.svg';
import qaSvg from '../assets/flags/qa.svg';
import reSvg from '../assets/flags/re.svg';
import roSvg from '../assets/flags/ro.svg';
import rsSvg from '../assets/flags/rs.svg';
import ruSvg from '../assets/flags/ru.svg';
import rwSvg from '../assets/flags/rw.svg';
import saSvg from '../assets/flags/sa.svg';
import sbSvg from '../assets/flags/sb.svg';
import scSvg from '../assets/flags/sc.svg';
import sdSvg from '../assets/flags/sd.svg';
import seSvg from '../assets/flags/se.svg';
import sgSvg from '../assets/flags/sg.svg';
import sh_acSvg from '../assets/flags/sh-ac.svg';
import sh_hlSvg from '../assets/flags/sh-hl.svg';
import sh_taSvg from '../assets/flags/sh-ta.svg';
import shSvg from '../assets/flags/sh.svg';
import siSvg from '../assets/flags/si.svg';
import sjSvg from '../assets/flags/sj.svg';
import skSvg from '../assets/flags/sk.svg';
import slSvg from '../assets/flags/sl.svg';
import smSvg from '../assets/flags/sm.svg';
import snSvg from '../assets/flags/sn.svg';
import soSvg from '../assets/flags/so.svg';
import srSvg from '../assets/flags/sr.svg';
import ssSvg from '../assets/flags/ss.svg';
import stSvg from '../assets/flags/st.svg';
import svSvg from '../assets/flags/sv.svg';
import sxSvg from '../assets/flags/sx.svg';
import sySvg from '../assets/flags/sy.svg';
import szSvg from '../assets/flags/sz.svg';
import tcSvg from '../assets/flags/tc.svg';
import tdSvg from '../assets/flags/td.svg';
import tfSvg from '../assets/flags/tf.svg';
import tgSvg from '../assets/flags/tg.svg';
import thSvg from '../assets/flags/th.svg';
import tjSvg from '../assets/flags/tj.svg';
import tkSvg from '../assets/flags/tk.svg';
import tlSvg from '../assets/flags/tl.svg';
import tmSvg from '../assets/flags/tm.svg';
import tnSvg from '../assets/flags/tn.svg';
import toSvg from '../assets/flags/to.svg';
import trSvg from '../assets/flags/tr.svg';
import ttSvg from '../assets/flags/tt.svg';
import tvSvg from '../assets/flags/tv.svg';
import twSvg from '../assets/flags/tw.svg';
import tzSvg from '../assets/flags/tz.svg';
import uaSvg from '../assets/flags/ua.svg';
import ugSvg from '../assets/flags/ug.svg';
import umSvg from '../assets/flags/um.svg';
import unSvg from '../assets/flags/un.svg';
import usSvg from '../assets/flags/us.svg';
import uySvg from '../assets/flags/uy.svg';
import uzSvg from '../assets/flags/uz.svg';
import vaSvg from '../assets/flags/va.svg';
import vcSvg from '../assets/flags/vc.svg';
import veSvg from '../assets/flags/ve.svg';
import vgSvg from '../assets/flags/vg.svg';
import viSvg from '../assets/flags/vi.svg';
import vnSvg from '../assets/flags/vn.svg';
import vuSvg from '../assets/flags/vu.svg';
import wfSvg from '../assets/flags/wf.svg';
import wsSvg from '../assets/flags/ws.svg';
import xkSvg from '../assets/flags/xk.svg';
import xxSvg from '../assets/flags/xx.svg';
import yeSvg from '../assets/flags/ye.svg';
import ytSvg from '../assets/flags/yt.svg';
import zaSvg from '../assets/flags/za.svg';
import zmSvg from '../assets/flags/zm.svg';
import zwSvg from '../assets/flags/zw.svg';

/**
 * Static mapping of all SVG flags.
 */
export const staticSvgMap: Record<string, string> = {
  ad: adSvg,
  ae: aeSvg,
  af: afSvg,
  ag: agSvg,
  ai: aiSvg,
  al: alSvg,
  am: amSvg,
  ao: aoSvg,
  aq: aqSvg,
  ar: arSvg,
  arab: arabSvg,
  as: asSvg,
  asean: aseanSvg,
  at: atSvg,
  au: auSvg,
  aw: awSvg,
  ax: axSvg,
  az: azSvg,
  ba: baSvg,
  bb: bbSvg,
  bd: bdSvg,
  be: beSvg,
  bf: bfSvg,
  bg: bgSvg,
  bh: bhSvg,
  bi: biSvg,
  bj: bjSvg,
  bl: blSvg,
  bm: bmSvg,
  bn: bnSvg,
  bo: boSvg,
  bq: bqSvg,
  br: brSvg,
  bs: bsSvg,
  bt: btSvg,
  bv: bvSvg,
  bw: bwSvg,
  by: bySvg,
  bz: bzSvg,
  ca: caSvg,
  cc: ccSvg,
  cd: cdSvg,
  cefta: ceftaSvg,
  cf: cfSvg,
  cg: cgSvg,
  ch: chSvg,
  ci: ciSvg,
  ck: ckSvg,
  cl: clSvg,
  cm: cmSvg,
  cn: cnSvg,
  co: coSvg,
  cp: cpSvg,
  cr: crSvg,
  cu: cuSvg,
  cv: cvSvg,
  cw: cwSvg,
  cx: cxSvg,
  cy: cySvg,
  cz: czSvg,
  de: deSvg,
  dg: dgSvg,
  dj: djSvg,
  dk: dkSvg,
  dm: dmSvg,
  do: doSvg,
  dz: dzSvg,
  eac: eacSvg,
  ec: ecSvg,
  ee: eeSvg,
  eg: egSvg,
  eh: ehSvg,
  er: erSvg,
  'es-ct': es_ctSvg,
  'es-ga': es_gaSvg,
  'es-pv': es_pvSvg,
  es: esSvg,
  et: etSvg,
  eu: euSvg,
  'example-us': example_usSvg,
  fi: fiSvg,
  fj: fjSvg,
  fk: fkSvg,
  fm: fmSvg,
  fo: foSvg,
  fr: frSvg,
  ga: gaSvg,
  'gb-eng': gb_engSvg,
  'gb-nir': gb_nirSvg,
  'gb-sct': gb_sctSvg,
  'gb-wls': gb_wlsSvg,
  gb: gbSvg,
  gd: gdSvg,
  ge: geSvg,
  gf: gfSvg,
  gg: ggSvg,
  gh: ghSvg,
  gi: giSvg,
  gl: glSvg,
  gm: gmSvg,
  gn: gnSvg,
  gp: gpSvg,
  gq: gqSvg,
  gr: grSvg,
  gs: gsSvg,
  gt: gtSvg,
  gu: guSvg,
  gw: gwSvg,
  gy: gySvg,
  hk: hkSvg,
  hm: hmSvg,
  hn: hnSvg,
  hr: hrSvg,
  ht: htSvg,
  hu: huSvg,
  ic: icSvg,
  id: idSvg,
  ie: ieSvg,
  il: ilSvg,
  im: imSvg,
  in: inSvg,
  io: ioSvg,
  iq: iqSvg,
  ir: irSvg,
  is: isSvg,
  it: itSvg,
  je: jeSvg,
  jm: jmSvg,
  jo: joSvg,
  jp: jpSvg,
  ke: keSvg,
  kg: kgSvg,
  kh: khSvg,
  ki: kiSvg,
  km: kmSvg,
  kn: knSvg,
  kp: kpSvg,
  kr: krSvg,
  kw: kwSvg,
  ky: kySvg,
  kz: kzSvg,
  la: laSvg,
  lb: lbSvg,
  lc: lcSvg,
  li: liSvg,
  lk: lkSvg,
  lr: lrSvg,
  ls: lsSvg,
  lt: ltSvg,
  lu: luSvg,
  lv: lvSvg,
  ly: lySvg,
  ma: maSvg,
  mc: mcSvg,
  md: mdSvg,
  me: meSvg,
  mf: mfSvg,
  mg: mgSvg,
  mh: mhSvg,
  mk: mkSvg,
  ml: mlSvg,
  mm: mmSvg,
  mn: mnSvg,
  mo: moSvg,
  mp: mpSvg,
  mq: mqSvg,
  mr: mrSvg,
  ms: msSvg,
  mt: mtSvg,
  mu: muSvg,
  mv: mvSvg,
  mw: mwSvg,
  mx: mxSvg,
  my: mySvg,
  mz: mzSvg,
  na: naSvg,
  nc: ncSvg,
  ne: neSvg,
  nf: nfSvg,
  ng: ngSvg,
  ni: niSvg,
  nl: nlSvg,
  no: noSvg,
  np: npSvg,
  nr: nrSvg,
  nu: nuSvg,
  nz: nzSvg,
  om: omSvg,
  pa: paSvg,
  pc: pcSvg,
  pe: peSvg,
  pf: pfSvg,
  pg: pgSvg,
  ph: phSvg,
  pk: pkSvg,
  pl: plSvg,
  pm: pmSvg,
  pn: pnSvg,
  pr: prSvg,
  ps: psSvg,
  pt: ptSvg,
  pw: pwSvg,
  py: pySvg,
  qa: qaSvg,
  re: reSvg,
  ro: roSvg,
  rs: rsSvg,
  ru: ruSvg,
  rw: rwSvg,
  sa: saSvg,
  sb: sbSvg,
  sc: scSvg,
  sd: sdSvg,
  se: seSvg,
  sg: sgSvg,
  'sh-ac': sh_acSvg,
  'sh-hl': sh_hlSvg,
  'sh-ta': sh_taSvg,
  sh: shSvg,
  si: siSvg,
  sj: sjSvg,
  sk: skSvg,
  sl: slSvg,
  sm: smSvg,
  sn: snSvg,
  so: soSvg,
  sr: srSvg,
  ss: ssSvg,
  st: stSvg,
  sv: svSvg,
  sx: sxSvg,
  sy: sySvg,
  sz: szSvg,
  tc: tcSvg,
  td: tdSvg,
  tf: tfSvg,
  tg: tgSvg,
  th: thSvg,
  tj: tjSvg,
  tk: tkSvg,
  tl: tlSvg,
  tm: tmSvg,
  tn: tnSvg,
  to: toSvg,
  tr: trSvg,
  tt: ttSvg,
  tv: tvSvg,
  tw: twSvg,
  tz: tzSvg,
  ua: uaSvg,
  ug: ugSvg,
  um: umSvg,
  un: unSvg,
  us: usSvg,
  uy: uySvg,
  uz: uzSvg,
  va: vaSvg,
  vc: vcSvg,
  ve: veSvg,
  vg: vgSvg,
  vi: viSvg,
  vn: vnSvg,
  vu: vuSvg,
  wf: wfSvg,
  ws: wsSvg,
  xk: xkSvg,
  xx: xxSvg,
  ye: yeSvg,
  yt: ytSvg,
  za: zaSvg,
  zm: zmSvg,
  zw: zwSvg,
};

/**
 * Get SVG content from static mapping.
 * @param countryCode The country code to look up in the static SVG map.
 * @returns The SVG content as a string if found, otherwise null.
 */
export function getStaticSvg(countryCode: string): string | null {
  return staticSvgMap[countryCode.toLowerCase()] || null;
}
